baseURL: 'http://theseluckystars.com/'
languageCode: 'en-us'
title: 'These Lucky Stars'

module:
  imports:
  - path: "github.com/alex-shpak/hugo-book"
  
params:
 BookTheme: "dark"
 BookFavicon: "SiB-favicon.ico"
 BookLogo: "SiB-logo.png"
 BookComments: false
 BooktoC: false
 BookEditPages: false
 BookSection: '*'
 