#!/usr/bin/env python3
"""
worksheets.py — regenerate the Phase 3 audit worksheets from data/.

    python3 _discovery/tools/worksheets.py

Writes _discovery/04-phase3-worksheets.md: tag membership, orphaned blocks,
implicit edges, feature-prerequisite cross-checks, section-block heading
readiness, and a hand-written-vs-generated comparison of the Related sections.
Pure read + report; it never touches content. Re-run it after `builddata.py`.
"""
import json, os, re, collections

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
D = lambda *p: os.path.join(REPO, *p)

BLOCKS = json.load(open(D("data/blocks.json")))
B = {b["id"]: b for b in BLOCKS}
EDGES = json.load(open(D("data/edges.json")))
RELATED = json.load(open(D("data/related.json")))
IMPLICIT = json.load(open(D("_discovery/tools/implicit-edges.json")))

CATEGORY_TAGS = {"core", "sci-fi", "fantasy"}
# Cohort gaps that are correct by design, so they never resurface as noise:
# `general` marks the General tab, so the Luck and Battery abilities are meant to
# lack it; framework blocks are not instances of the cohort they introduce.
FRAMEWORK = ("overview", "installation", "power-sources", "damage-and-wounds",
             "wounds", "common-injuries", "action-types")


def body_of(b):
    """A block's prose: no frontmatter, no headings, link targets stripped."""
    try:
        raw = open(D(b["file"])).read()
    except OSError:
        return ""
    txt = raw.split("---", 2)[2] if raw.startswith("---") else raw
    txt = re.sub(r"^#{1,6}.*$", "", txt, flags=re.M)
    return re.sub(r"\]\([^)]*\)", "]", txt).strip()


def first_sentence(b, limit=150):
    txt = re.sub(r"\s+", " ", body_of(b))
    txt = re.sub(r"[*_]{1,3}", "", txt)          # emphasis markers are not prose
    txt = re.sub(r"^[>|\-\s]+", "", txt).strip()
    m = re.search(r"^(.{0,%d}?[.!?])(\s|$)" % limit, txt)
    s = m.group(1) if m else txt[:limit]
    return s + ("…" if not m and len(txt) > limit else "")


def spot(note="your call"):
    """A pre-placed annotation slot, so notes need no copy-pasting."""
    w(f"  <!-- {note}: -->")


STRUCTURAL = {"equipment", "sci-fi", "core", "generic", "site-chrome", "character-creation"}
OVERVIEWISH = ("overview", "basics", "index")

out = []
w = out.append

w("# Phase 3 — audit worksheets")
w("")
w("Generated by `_discovery/tools/worksheets.py` from `data/`. Re-run it after")
w("`builddata.py` to refresh. Nothing here changes content — it is a review sheet.")
w("")
w(f"Corpus: **{len(BLOCKS)} blocks**, **{len(EDGES)} edges**, "
  f"**{sum(1 for b in BLOCKS if b.get('wip'))} wip**.")
w("")
w("## How to annotate this")
w("")
w("Every decision has an **empty HTML comment already sitting under it**:")
w("")
w("```")
w("- **`traits/alert`** \u2014 Alert")
w("  <!-- ok / new title: -->")
w("```")
w("")
w("Type inside it. Freehand \u2014 no fixed vocabulary, say what you mean and I will")
w("act on it. Leave a spot untouched and I will treat it as unreviewed and leave")
w("that item alone. The prompt text before the colon is a hint, not a menu.")
w("")
w("Regenerating this file **erases annotations**, so I will not re-run")
w("`worksheets.py` while a review is in flight.")
w("")
w("Suggested order, and why: **C5** (smallest, warms up the judgement), then")
w("**C1** (tag renames would otherwise invalidate C3's quoted fragments), then")
w("**C3** (the one that needs rewrites).")
w("")
w("---")
w("")

# ------------------------------------------------------------------ C1 tags ---
w("## C1. Tag membership")
w("")
w("Tag names are the query surface the PDF builder will use, so a hole here")
w("becomes a hole in the selection UI. The anomalies are listed first — those are")
w("the decisions. Full membership lists are at the end of the section, collapsed,")
w("for when you want to browse rather than review.")
w("")
tags = collections.defaultdict(list)
for b in BLOCKS:
    if b.get("excluded"):
        continue
    for tg in b.get("tags", []):
        tags[tg].append(b)
LIVE = [b for b in BLOCKS if not b.get("excluded")]
w(f"**{len(LIVE)} blocks, {len(tags)} distinct tags.**")
w("")

w("### C1a. Near-duplicate tag names")
w("")
w("Two tags whose names differ only by plural or punctuation. Either they mean")
w("different things and something should say so, or one should win.")
w("")
dupes = []
names = sorted(tags)
for a in names:
    for b2 in names:
        if a < b2 and (a + "s" == b2 or b2 + "s" == a
                       or a.replace("-", "") == b2.replace("-", "")):
            dupes.append((a, b2))
if dupes:
    for a, b2 in dupes:
        w(f"- **`{a}` ({len(tags[a])})** vs **`{b2}` ({len(tags[b2])})**")
        w(f"  - `{a}`: " + ", ".join(f"`{x['id']}`" for x in sorted(tags[a], key=lambda x: x["id"])))
        w(f"  - `{b2}`: " + ", ".join(f"`{x['id']}`" for x in sorted(tags[b2], key=lambda x: x["id"])))
        spot("merge into which, or keep both and why")
        w("")
else:
    w("- none")
    w("")

w("### C1b. Tags with two or fewer members")
w("")
w("A tag this small is either under-applied, redundant with a bigger tag, or a")
w("category of one that does not need to be a tag.")
w("")
small = sorted((tg for tg, m in tags.items() if len(m) <= 2), key=lambda tg: (len(tags[tg]), tg))
for tg in small:
    mem = sorted(tags[tg], key=lambda x: x["id"])
    w(f"- **`{tg}`** ({len(mem)}) — " + ", ".join(f"`{x['id']}`" for x in mem))
    spot("keep / merge into X / delete")
w("")

w("### C1c. Blocks with no tags at all")
w("")
w("Invisible to every tag query. Not necessarily wrong — a framework block may")
w("not belong to any group — but it should be a decision, not an oversight.")
w("")
untagged = [b for b in LIVE if not b.get("tags")]
for b in sorted(untagged, key=lambda b: b["id"]):
    w(f"- **`{b['id']}`** — {b['title']}  <sub>type={b['type']}</sub>")
    w(f"      {first_sentence(b, 110)}")
    spot("tags to add, or leave untagged")
w("" if untagged else "- none")
w("")

w("### C1d. Cohort gaps")
w("")
w("A tag carried by most of a namespace but missing from some members. Category")
w("tags (`core`, `sci-fi`) and framework blocks are excluded — those gaps are")
w("correct by definition and were only noise.")
w("")
ns = collections.defaultdict(list)
for b in LIVE:
    ns[b["id"].split("/")[0]].append(b)
gaps = []
for n, mem in sorted(ns.items()):
    if len(mem) < 4:
        continue
    cnt = collections.Counter(tg for x in mem for tg in x.get("tags", []))
    for tg, c in cnt.items():
        if tg in CATEGORY_TAGS or not 0.7 <= c / len(mem) < 1.0:
            continue
        miss = [x for x in mem
                if tg not in x.get("tags", []) and not x["id"].rsplit("/", 1)[1] in FRAMEWORK]
        if miss:
            gaps.append((n, tg, c, len(mem), miss))
if gaps:
    for n, tg, c, tot, miss in sorted(gaps, key=lambda r: -len(r[4])):
        w(f"- **`{tg}`** is on {c}/{tot} of `{n}/` — missing from {len(miss)}:")
        for x in sorted(miss, key=lambda x: x["id"]):
            w(f"  - `{x['id']}` — {x['title']}")
        spot("expected (say why) / add the tag")
        w("")
else:
    w("- none")
    w("")

w("### C1e. Tags per block")
w("")
dist = collections.Counter(len(b.get("tags", [])) for b in LIVE)
w("| Tags | Blocks |")
w("|---|---|")
for k in sorted(dist):
    w(f"| {k} | {dist[k]} |")
w("")
w("A distribution to eyeball, not a list of decisions. A single-tag block is fine")
w("if that tag is the functional one; it is thin if the tag is structural.")
spot("anything look wrong here")
w("")

w("### Blocks a quick-reference table would show with an empty cell")
w("")
w("`summary` is what the generated tables print. A selectable block without one")
w("renders a blank cell on every catalog and module page that lists it.")
w("")
# what a table actually lists: selectable things, plus anything a generated
# catalog points at (a rules-additions table lists rule blocks too)
catalogued = {e["target"] for e in EDGES if e.get("class") == "catalog"}
missing = [b for b in BLOCKS
           if not b.get("summary") and not b.get("excluded")
           and b.get("selectable", True)
           and (b.get("type") in ("feature", "equipment", "creature")
                or b["id"] in catalogued)]
by_type = collections.defaultdict(list)
for b in missing:
    by_type[b["type"]].append(b)
w(f"**{len(missing)} blocks**")
w("")
for t in sorted(by_type):
    w(f"*{t}*")
    w("")
    for b in sorted(by_type[t], key=lambda b: b["id"]):
        page = (b.get("source_page") or "?").replace("content/docs/free-srd/", "")
        w(f"- `{b['id']}` — {b['title']}  <sub>{page}</sub>")
    w("")

w("### C1f. Blocks with only structural tags")
w("")
w("These carry no functional tag, so a tag-as-query pull (\"give me all the")
w("grenades\") cannot reach them. Structural tags are "
  + ", ".join(f"`{s}`" for s in sorted(STRUCTURAL)) + ".")
w("")
thin = [b for b in LIVE
        if b.get("tags") and not (set(b["tags"]) - STRUCTURAL)]
if thin:
    for b in sorted(thin, key=lambda b: b["id"]):
        w(f"- **`{b['id']}`** — {b['title']}  <sub>{', '.join(b['tags'])}</sub>")
        w(f"      {first_sentence(b, 110)}")
        spot("functional tag to add, or fine as-is")
else:
    w("- none")
w("")

w("### C1g. Full membership lists")
w("")
w("Reference, not review — every tag with every member. Collapsed so it does not")
w("bury the decisions above.")
w("")
w("<details><summary>All " + str(len(tags)) + " tags</summary>")
w("")
for tg, members in sorted(tags.items(), key=lambda kv: (-len(kv[1]), kv[0])):
    w(f"**`{tg}`** — {len(members)}")
    w("")
    for b in sorted(members, key=lambda b: b["id"]):
        others = [x for x in b["tags"] if x != tg]
        w(f"- `{b['id']}` — {b['title']}"
          + (f"  <sub>{', '.join(others)}</sub>" if others else "  <sub>(only tag)</sub>"))
    w("")
w("</details>")
w("")
w("---")
w("")

# --------------------------------------------------------------- C2 orphans ---
w("## C2. Reference / edge review")
w("")
types = collections.Counter(e["type"] for e in EDGES)
w("| Edge type | Count |")
w("|---|---|")
for t, n in sorted(types.items(), key=lambda kv: -kv[1]):
    w(f"| `{t}` | {n} |")
w("")

w("### Orphans — no other block's prose points at these")
w("")
zero = [b for b in BLOCKS if b.get("in_degree", 0) == 0 and not b.get("excluded")]
listed = {e["target"] for e in EDGES if str(e["source"]).startswith("page:")}
unreachable = [b for b in zero if b["id"] not in listed]
w(f"**{len(zero)} blocks** have `in_degree: 0`, and **all but "
  f"{len(unreachable)}** of them are still reachable — they are listed in a")
w("`{{< catalog >}}` table or linked from page-frame prose. For a catalogued")
w("item (a grenade, an ability) that is the normal, expected state, so the only")
w("rows worth reviewing are the **rules and reference blocks**: a rule nothing")
w("else links to may be a missing cross-reference rather than a standalone rule.")
w("")
if unreachable:
    w("**Genuinely unreachable — not linked, not catalogued:**")
    w("")
    for b in sorted(unreachable, key=lambda b: b["id"]):
        w(f"- `{b['id']}` — {b['title']}")
    w("")
orphans = [b for b in zero
           if b.get("type") in ("rule", "reference")
           and not any(k in b["id"].split("/")[-1] for k in OVERVIEWISH)]
w(f"Rule/reference blocks with no inbound prose link: **{len(orphans)}**")
w("")
w("| Block | Type | Lives on |")
w("|---|---|---|")
for b in sorted(orphans, key=lambda b: (b.get("source_page") or "", b["id"])):
    page = (b.get("source_page") or "?").replace("content/docs/free-srd/", "")
    w(f"| `{b['id']}` — {b['title']} | {b.get('type','')} | {page} |")
w("")

w("### Implicit edges — rule couplings with no link in the prose")
w("")
w("These are invisible while reading. Decide per row: leave implicit, or write a")
w("real in-text link.")
w("")
w("| From | To | Why it is coupled |")
w("|---|---|---|")
for e in IMPLICIT:
    w(f"| `{e['source']}` | `{e['target']}` | {e.get('note','')} |")
w("")
w("---")
w("")

# ------------------------------------------------------- C4 feature prereqs ---
w("## C4. Feature prerequisites — the three places they are written")
w("")
w("A feature's prerequisites are stated in three places, each doing a different")
w("job. This section reports where they disagree, so drift surfaces instead of")
w("sitting in the data.")
w("")
w("1. **The prerequisite line** in the block's own text — what a reader sees.")
w("2. **`requires:`** in frontmatter — the mechanical rule the PDF builder obeys.")
w("   By decision it holds *features only*: attributes, levels, items and")
w("   category conditions (\"any tool kit\") stay prose.")
w("3. **The index nesting** (`- ` / `-- ` in a catalog) — where a reader meets")
w("   the entry. Recorded as `listed_under`.")
w("")
w("**2 and 3 are not the same thing and must not be merged.** They agree today,")
w("but 39 `requires` point into a different list entirely, which no index tree")
w("can show — so neither can be generated from the other.")
w("")

URL2ID = {}
for bid, b in B.items():
    if b.get("url"):
        URL2ID[b["url"]] = bid
    if b.get("anchor"):
        URL2ID.setdefault("#" + b["anchor"], bid)


def prereq_line(b):
    try:
        body = open(D(b["file"])).read().split("\n---", 1)[1]
    except (OSError, IndexError):
        return ""
    for ln in body.split("\n"):
        t = ln.strip()
        if t.startswith("*") and t.endswith("*") and not t.startswith("**") and len(t) > 4:
            return t.strip("*").strip()
    return ""


def derived_requires(b):
    """What `requires` would be if generated from the prerequisite line."""
    out = set()
    for _, url in re.findall(r"\[([^\]]+)\]\(([^)]+)\)", prereq_line(b)):
        hit = URL2ID.get(url)
        if hit and B[hit]["type"] == "feature":
            out.add(hit)
    return out


feats = [b for b in BLOCKS if b["type"] == "feature" and b["home"] == "snippet"]
drift = [(b, sorted(set(b.get("requires") or []) - derived_requires(b)),
             sorted(derived_requires(b) - set(b.get("requires") or [])))
         for b in feats]
drift = [d for d in drift if d[1] or d[2]]

w("### `requires` against the prerequisite line")
w("")
if drift:
    w(f"**{len(drift)} features disagree.** Either the line names a feature the")
    w("frontmatter does not record, or the frontmatter records one the line does")
    w("not mention.")
    w("")
    w("| Block | In `requires`, not linked in the line | Linked in the line, not in `requires` |")
    w("|---|---|---|")
    for b, missing, extra in drift:
        w(f"| `{b['id']}` | {', '.join(f'`{m}`' for m in missing) or '—'} "
          f"| {', '.join(f'`{e}`' for e in extra) or '—'} |")
else:
    w(f"**No disagreements** across {sum(1 for b in feats if b.get('requires'))} features "
      "that carry `requires`.")
    w("")
    w("Every one is exactly the set of feature links in its own prerequisite line,")
    w("which means `requires` is currently *derivable* rather than independent —")
    w("worth knowing before deciding to keep maintaining it by hand.")
w("")

w("### `requires` against the index nesting")
w("")
w("Differences here are expected — the two answer different questions. Read it")
w("as a review list, not an error list.")
w("")
nested = [b for b in BLOCKS if b.get("listed_under")]
rows = []
for b in nested:
    req = set(b.get("requires") or [])
    if b["listed_under"] in req:
        continue
    rows.append((b, req))
w(f"{len(nested)} blocks are nested in an index; **{len(rows)}** are nested under")
w("something they do not require.")
w("")
if rows:
    w("| Block | Listed under | Actually requires |")
    w("|---|---|---|")
    for b, req in rows:
        w(f"| `{b['id']}` | `{b['listed_under']}` | "
          f"{', '.join(f'`{r}`' for r in sorted(req)) or '— nothing recorded —'} |")
w("")

crossns = 0
for b in feats:
    ns = b["id"].split("/")[0]
    crossns += sum(1 for r in (b.get("requires") or []) if r.split("/")[0] != ns)
w(f"Also worth remembering: **{crossns}** `requires` point at a feature in another")
w("list (abilities depending on proficiencies or traits). No index tree can show")
w("those, which is the other reason the nesting cannot be generated from them.")
w("")
w("---")
w("")

# ------------------------------------------------ C3 self-containment ---
w("## C3. Self-containment — blocks that point outside themselves")
w("")
w("A block has to read correctly when a GM prints it alone, with none of its")
w("page around it. This flags **deictic language** — text pointing at something")
w("outside the block: `above`, `below`, `this page`, `the following`,")
w("`as described`, `see the`.")
w("")
w("Two filters run first, or the list is mostly noise:")
w("")
w("- **Comparisons are dropped.** \"stress drops below threshold\" and \"well below")
w("  max carry weight\" are measurements, not pointers.")
w("- **In-block referents are dropped.** \"use the chart below\" is fine when the")
w("  chart is the next line of the same block. Those are listed separately.")
w("")
w("Then the rule that decides severity: **a pointer that is a link is fine.**")
w("`see the [Martial Training] proficiency` survives being printed alone — the")
w("reader can follow it. **Unlinked deixis is the bug**, because nothing in the")
w("printed page tells the reader where to look.")
w("")

C3_PATS = [
    ("above/below",        r"\b(above|below)\b"),
    ("this/these <thing>", r"\b(this|these)\s+(section|page|chapter|list|table|chart)\b"),
    ("as noted/described", r"\bas (noted|described|mentioned|shown|stated|listed)\b"),
    ("see the/above/below", r"\bsee (the|below|above)\b"),
    ("earlier/previous",   r"\b(earlier|previously|previous)\b"),
    ("the following",      r"\bthe following\b"),
    ("\u2026here",             r"\b(listed|shown|described|found) here\b"),
]
# words that make "below"/"above" a measurement rather than a direction
COMPARE = r"(lowered|lower|drops?|falls?|reduce[sd]?|well|beyond|but|is|are|stays?|remains?|at or)\s+(\w+\s+)?$"

def c3_scan():
    inblock, outside = [], []
    for b in sorted(LIVE, key=lambda x: x["id"]):
        txt = body_of(b)
        if not txt:
            continue
        for name, pat in C3_PATS:
            hit = None
            for m in re.finditer(pat, txt, re.I):
                before, after = txt[: m.start()], txt[m.end():]
                word = m.group(0).lower()
                if re.search(COMPARE, before[-40:], re.I):
                    continue
                selfref = (("below" in word or "following" in word)
                           and re.search(r"^\s*[|>\-*]", after, re.M)) or \
                          ("above" in word and re.search(r"^\s*[|>]", before, re.M))
                frag = re.sub(r"\s+", " ", txt[max(0, m.start() - 55): m.end() + 55])
                # was the pointer written as a link? body_of() left "]" behind
                linked = "]" in txt[max(0, m.start() - 30): m.end() + 30]
                hit = (b, name, frag, linked, selfref)
                break
            if hit:
                (inblock if hit[4] else outside).append(hit)
                break
    return inblock, outside

inblock, outside = c3_scan()
unlinked = [h for h in outside if not h[3]]
linked = [h for h in outside if h[3]]

w(f"Scanned {len(LIVE)} blocks. **{len(outside)}** point outside themselves; of")
w(f"those **{len(unlinked)}** do it without a link. A further {len(inblock)} point at")
w("something inside their own block and are listed last as a sanity check.")
w("")

w(f"### C3a. Unlinked pointers — {len(unlinked)} blocks")
w("")
w("**These are the ones that break when printed alone.** Most are a one-sentence")
w("rewrite: name the thing instead of gesturing at it, or add the link.")
w("")
for b, name, frag, _, _ in unlinked:
    page = (b.get("source_page") or "?").replace("content/docs/free-srd/", "")
    w(f"- **`{b['id']}`** — {b['title']}  <sub>{page}</sub>  `[{name}]`")
    w(f"      \u2026{frag}\u2026")
    spot("rewrite / add link / fine as-is")
w("" if unlinked else "- none")
w("")

w(f"### C3b. Linked pointers — {len(linked)} blocks")
w("")
w("The pointer is a link, so a reader can follow it out of a printed page. Listed")
w("for completeness; skip unless one reads badly.")
w("")
for b, name, frag, _, _ in linked:
    w(f"- `{b['id']}` — {b['title']}  `[{name}]`")
    w(f"      \u2026{frag}\u2026")
w("" if linked else "- none")
w("")

w(f"### C3c. Points at its own content — {len(inblock)} blocks")
w("")
w("\"The chart below\" where the chart is in the same block. Correct as written —")
w("here so you can confirm the filter is not hiding a real problem.")
w("")
w("<details><summary>" + str(len(inblock)) + " blocks</summary>")
w("")
for b, name, frag, _, _ in inblock:
    w(f"- `{b['id']}` `[{name}]` \u2026{frag}\u2026")
w("")
w("</details>")
w("")
w("---")
w("")

# ---------------------------------------------------- C5 headings for print ---
w("## C5. Section-block titles — what the PDF builder will print")
w("")
w("104 blocks carry no heading of their own; the host page supplies one. Anything")
w("re-assembling them elsewhere — `{{< blockset >}}` today, the PDF builder later —")
w("prints `title` instead. For most of them that title has already been proofread,")
w("because it *is* the heading a reader sees. For a few it has never been rendered")
w("anywhere, and those are the ones that can print wrong.")
w("")
w("This is how `sci-fi/huds` was caught printing \"Huds\" instead of")
w("\"Heads Up Displays (HUDs)\".")
w("")

sec = [b for b in BLOCKS if not b["owns_heading"] and not b.get("excluded")
       and b.get("source_page")]
byhead = collections.Counter((b["source_page"], b["anchor"]) for b in sec)
shared = [b for b in sec if byhead[(b["source_page"], b["anchor"])] > 1]

w(f"### Titles that have never been a heading — {len(shared)} blocks")
w("")
w("These sit under a heading they share with other blocks, so that heading names")
w("the *group*, not the block \u2014 the block's own `title` was never a heading a")
w("reader saw.")
w("")
w("**But most of them state their name anyway**, as a bold lead-in on the first")
w("line: `**Disarm** *(3 AP)* \u2014 Attempt to\u2026`. Where that happens the title has")
w("been proofread after all, and the builder would print the same words. So this")
w("splits into a short list that needs a decision and a longer one to confirm.")
w("")
def names_itself(b):
    """True if the block opens by stating its own name in bold.

    Many section blocks do -- `**Disarm** *(3 AP)* - ...`. That name IS rendered
    on the page, so the title has been proofread after all; it just is not a
    heading. Only the blocks that never state their name are unreviewed.
    """
    head = re.sub(r"\s+", " ", body_of(b))[:120].lstrip("> ")
    m = re.match(r"\*\*([^*]+?)\*\*", head)
    if not m:
        return None
    lead = m.group(1).strip().rstrip(":=").strip()
    return lead if lead.lower().startswith(b["title"].lower()[:12]) else None

confirmed = [b for b in shared if names_itself(b)]
unseen = [b for b in shared if not names_itself(b)]

w(f"#### Never stated anywhere \u2014 {len(unseen)} blocks, these need a decision")
w("")
w("Nothing on the page prints this block's name, in any form. Whatever the PDF")
w("builder prints is text no reader has ever checked.")
w("")
for b in sorted(unseen, key=lambda b: b["id"]):
    page = b["source_page"].replace("content/docs/free-srd/", "")
    w(f"- **`{b['id']}`** \u2192 would print **\u201c{b['title']}\u201d**"
      f"  <sub>under `#{b['anchor']}` on {page}</sub>")
    w(f"      opens: {first_sentence(b, 130)}")
    spot("ok / new title")
w("" if unseen else "- none")
w("")
w(f"#### Already stated as a bold lead-in \u2014 {len(confirmed)} blocks, confirm only")
w("")
w("These open by naming themselves \u2014 `**Disarm** *(3 AP)* \u2014 Attempt to\u2026` \u2014 so the")
w("name **is** on the page and has been read, just as prose rather than a heading.")
w("The builder would print the same words. Skim for anything that reads oddly as a")
w("standalone heading; otherwise this is a no-op.")
w("")
for b in sorted(confirmed, key=lambda b: b["id"]):
    w(f"- `{b['id']}` \u2014 bold lead-in \u201c{names_itself(b)}\u201d, title \u201c{b['title']}\u201d"
      + ("  **\u2190 differ**" if names_itself(b) != b["title"] else ""))
w("")
spot("anything in this list read wrong as a heading")
w("")
w("<details><summary>Full detail for all " + str(len(shared)) + ", grouped by shared heading</summary>")
w("")

groups = collections.defaultdict(list)
for b in shared:
    groups[(b["source_page"], b["anchor"])].append(b)
for (page, anchor), mem in sorted(groups.items()):
    short = page.replace("content/docs/free-srd/", "")
    w(f"**Under `#{anchor}` on {short}** — {len(mem)} blocks share this heading")
    w("")
    for b in sorted(mem, key=lambda b: b["id"]):
        sibs = [x["title"] for x in sorted(mem, key=lambda x: x["id"]) if x["id"] != b["id"]]
        w(f"- `{b['id']}` → would print **\u201c{b['title']}\u201d**")
        w(f"      beside: {', '.join(sibs) if sibs else '(none)'}")
        w(f"      opens: {first_sentence(b, 130)}")
    w("")
w("</details>")
w("")

w(f"The other {len(sec) - len(shared)} are the sole block under their heading, so their")
w("title is that heading and has been proofread by being read.")
w("")

w("### Heading level is the bigger print problem")
w("")
lv = collections.Counter()
for b in BLOCKS:
    if b["owns_heading"] and b["home"] == "snippet":
        try:
            body = open(D(b["file"])).read().split("\n---", 1)[1]
        except (OSError, IndexError):
            continue
        m = re.search(r"^(#{1,6})\s", body, re.M)
        if m:
            lv[len(m.group(1))] += 1
w("The blocks that *own* a heading hard-code its level in their markdown:")
w("")
for k in sorted(lv):
    w(f"- **h{k}** — {lv[k]} blocks")
w("")
w("So a GM who assembles a PDF and puts one of those at a different depth gets a")
w("heading at the wrong level, and the markdown cannot bend. The 104 blocks with")
w("*no* heading are the flexible ones — they carry a title and let whatever renders")
w("them choose the level.")
w("")
w("**The builder should print every block the same way: take `title`, choose the")
w("level from where the GM placed it, and skip the block's own leading heading")
w("when `owns_heading` is true.** That pair of fields is exactly what makes the")
w("normalisation possible — no content change needed, and the two shapes stop")
w("mattering at print time.")
w("")
w("---")
w("")

# --------------------------------------------------------------- D related ---
w("## D. Related sections — hand-written vs generated")
w("")
w("`{{< related >}}` renders the generated column. The hand-written lists carry")
w("editorial judgement the edge graph does not have (they point where a reader")
w("*should* go next, not only where the prose happens to link), so this is a")
w("per-page call, not a global swap.")
w("")
for page in sorted(RELATED):
    src = open(D(page)).read()
    hand = re.findall(r"^- \[([^\]]+)\]\(([^)]+)\)", src[src.find("## Related"):], re.M) \
        if "## Related" in src else []
    gen = RELATED[page]
    if not hand and "{{< related >}}" in src:
        continue   # already converted
    if not hand:
        continue   # no hand-written list to compare against
    w(f"### `{page.replace('content/docs/free-srd/', '')}`")
    w("")
    w("| Hand-written | Generated (in order) |")
    w("|---|---|")
    for i in range(max(len(hand), len(gen))):
        h = hand[i][0] if i < len(hand) else ""
        g = (f"{gen[i]['title']} <sub>out {gen[i]['out']} / in {gen[i]['in']}</sub>"
             if i < len(gen) else "")
        w(f"| {h} | {g} |")
    only_hand = {h[0].split(" — ")[0] for h in hand} - {g["title"] for g in gen}
    only_gen = {g["title"] for g in gen} - {h[0].split(" — ")[0] for h in hand}
    if only_hand:
        w("")
        w(f"*Generated would drop:* {', '.join(sorted(only_hand))}")
    if only_gen:
        w(f"*Generated would add:* {', '.join(sorted(only_gen))}")
    w("")

w("### Pages with a generated list and no hand-written one")
w("")
w("Free wins — these pages currently end with no Related section at all.")
w("")
for page in sorted(RELATED):
    src = open(D(page)).read()
    if "## Related" in src:
        continue
    names = ", ".join(g["title"] for g in RELATED[page][:6])
    w(f"- `{page.replace('content/docs/free-srd/', '')}` → {names}")
w("")

path = D("_discovery/04-phase3-worksheets.md")
open(path, "w").write("\n".join(out) + "\n")
print(f"wrote {os.path.relpath(path, REPO)} ({len(out)} lines)")
print(f"  {len(tags)} tags, {len(orphans)} orphans, {len(missing)} missing summaries, "
      f"{len(IMPLICIT)} implicit edges, {len(RELATED)} pages with related data")
