#!/usr/bin/env python3
"""
worksheets.py — regenerate the Phase 3 audit worksheets from data/.

    python3 _discovery/tools/worksheets.py

Writes _discovery/04-phase3-worksheets.md: tag membership, orphaned blocks,
implicit edges, and a hand-written-vs-generated comparison of the Related
sections. Pure read + report; it never touches content. Re-run it after
`builddata.py` whenever you want a fresh review sheet.
"""
import json, os, re, collections

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
D = lambda *p: os.path.join(REPO, *p)

BLOCKS = json.load(open(D("data/blocks.json")))
B = {b["id"]: b for b in BLOCKS}
EDGES = json.load(open(D("data/edges.json")))
RELATED = json.load(open(D("data/related.json")))
IMPLICIT = json.load(open(D("_discovery/tools/implicit-edges.json")))

STRUCTURAL = {"equipment", "sci-fi", "core", "generic", "site-chrome", "character-creation"}
OVERVIEWISH = ("overview", "basics", "index")

out = []
w = out.append

w("# Phase 3 — audit worksheets")
w("")
w("Generated by `_discovery/tools/worksheets.py` from `data/`. Re-run it after")
w("`builddata.py` to refresh. Nothing here changes content — it is a review sheet.")
w("")
w(f"Corpus: **{len(BLOCKS)} blocks**, **{len(EDGES)} edges**, "
  f"**{sum(1 for b in BLOCKS if b.get('wip'))} wip**.")
w("")
w("---")
w("")

# ------------------------------------------------------------------ C1 tags ---
w("## C1. Tag membership")
w("")
w("Scan each list for holes — a block that belongs but is missing, or a member")
w("that does not fit. Tag names are the query surface the PDF builder will use.")
w("")
tags = collections.defaultdict(list)
for b in BLOCKS:
    for t in b.get("tags", []):
        tags[t].append(b)
for t, members in sorted(tags.items(), key=lambda kv: (-len(kv[1]), kv[0])):
    w(f"### `{t}` — {len(members)}")
    w("")
    for b in sorted(members, key=lambda b: b["id"]):
        others = [x for x in b["tags"] if x != t]
        w(f"- `{b['id']}` — {b['title']}"
          + (f"  <sub>{', '.join(others)}</sub>" if others else "  <sub>(only tag)</sub>"))
    w("")

w("### Blocks a quick-reference table would show with an empty cell")
w("")
w("`summary` is what the generated tables print. A selectable block without one")
w("renders a blank cell on every catalog and module page that lists it.")
w("")
# what a table actually lists: selectable things, plus anything a generated
# catalog points at (a rules-additions table lists rule blocks too)
catalogued = {e["target"] for e in EDGES if e.get("class") == "catalog"}
missing = [b for b in BLOCKS
           if not b.get("summary") and not b.get("excluded")
           and b.get("selectable", True)
           and (b.get("type") in ("feature", "equipment", "creature")
                or b["id"] in catalogued)]
by_type = collections.defaultdict(list)
for b in missing:
    by_type[b["type"]].append(b)
w(f"**{len(missing)} blocks**")
w("")
for t in sorted(by_type):
    w(f"*{t}*")
    w("")
    for b in sorted(by_type[t], key=lambda b: b["id"]):
        page = (b.get("source_page") or "?").replace("content/docs/free-srd/", "")
        w(f"- `{b['id']}` — {b['title']}  <sub>{page}</sub>")
    w("")

w("### Blocks with only structural tags")
w("")
w("These carry no functional tag, so a tag-as-query pull (\"give me all the")
w("grenades\") cannot reach them.")
w("")
thin = [b for b in BLOCKS
        if b.get("tags") and not (set(b["tags"]) - STRUCTURAL) and not b.get("excluded")]
if thin:
    for b in sorted(thin, key=lambda b: b["id"]):
        w(f"- `{b['id']}` — {b['title']}  <sub>{', '.join(b['tags'])}</sub>")
else:
    w("- none")
w("")
untagged = [b for b in BLOCKS if not b.get("tags")]
w(f"Blocks with no tags at all: **{len(untagged)}**"
  + ("" if not untagged else " — " + ", ".join(f"`{b['id']}`" for b in untagged)))
w("")
w("---")
w("")

# --------------------------------------------------------------- C2 orphans ---
w("## C2. Reference / edge review")
w("")
types = collections.Counter(e["type"] for e in EDGES)
w("| Edge type | Count |")
w("|---|---|")
for t, n in sorted(types.items(), key=lambda kv: -kv[1]):
    w(f"| `{t}` | {n} |")
w("")

w("### Orphans — no other block's prose points at these")
w("")
zero = [b for b in BLOCKS if b.get("in_degree", 0) == 0 and not b.get("excluded")]
listed = {e["target"] for e in EDGES if str(e["source"]).startswith("page:")}
unreachable = [b for b in zero if b["id"] not in listed]
w(f"**{len(zero)} blocks** have `in_degree: 0`, and **all but "
  f"{len(unreachable)}** of them are still reachable — they are listed in a")
w("`{{< catalog >}}` table or linked from page-frame prose. For a catalogued")
w("item (a grenade, an ability) that is the normal, expected state, so the only")
w("rows worth reviewing are the **rules and reference blocks**: a rule nothing")
w("else links to may be a missing cross-reference rather than a standalone rule.")
w("")
if unreachable:
    w("**Genuinely unreachable — not linked, not catalogued:**")
    w("")
    for b in sorted(unreachable, key=lambda b: b["id"]):
        w(f"- `{b['id']}` — {b['title']}")
    w("")
orphans = [b for b in zero
           if b.get("type") in ("rule", "reference")
           and not any(k in b["id"].split("/")[-1] for k in OVERVIEWISH)]
w(f"Rule/reference blocks with no inbound prose link: **{len(orphans)}**")
w("")
w("| Block | Type | Lives on |")
w("|---|---|---|")
for b in sorted(orphans, key=lambda b: (b.get("source_page") or "", b["id"])):
    page = (b.get("source_page") or "?").replace("content/docs/free-srd/", "")
    w(f"| `{b['id']}` — {b['title']} | {b.get('type','')} | {page} |")
w("")

w("### Implicit edges — rule couplings with no link in the prose")
w("")
w("These are invisible while reading. Decide per row: leave implicit, or write a")
w("real in-text link.")
w("")
w("| From | To | Why it is coupled |")
w("|---|---|---|")
for e in IMPLICIT:
    w(f"| `{e['source']}` | `{e['target']}` | {e.get('note','')} |")
w("")
w("---")
w("")

# --------------------------------------------------------------- D related ---
w("## D. Related sections — hand-written vs generated")
w("")
w("`{{< related >}}` renders the generated column. The hand-written lists carry")
w("editorial judgement the edge graph does not have (they point where a reader")
w("*should* go next, not only where the prose happens to link), so this is a")
w("per-page call, not a global swap.")
w("")
for page in sorted(RELATED):
    src = open(D(page)).read()
    hand = re.findall(r"^- \[([^\]]+)\]\(([^)]+)\)", src[src.find("## Related"):], re.M) \
        if "## Related" in src else []
    gen = RELATED[page]
    if not hand and "{{< related >}}" in src:
        continue   # already converted
    if not hand:
        continue   # no hand-written list to compare against
    w(f"### `{page.replace('content/docs/free-srd/', '')}`")
    w("")
    w("| Hand-written | Generated (in order) |")
    w("|---|---|")
    for i in range(max(len(hand), len(gen))):
        h = hand[i][0] if i < len(hand) else ""
        g = (f"{gen[i]['title']} <sub>out {gen[i]['out']} / in {gen[i]['in']}</sub>"
             if i < len(gen) else "")
        w(f"| {h} | {g} |")
    only_hand = {h[0].split(" — ")[0] for h in hand} - {g["title"] for g in gen}
    only_gen = {g["title"] for g in gen} - {h[0].split(" — ")[0] for h in hand}
    if only_hand:
        w("")
        w(f"*Generated would drop:* {', '.join(sorted(only_hand))}")
    if only_gen:
        w(f"*Generated would add:* {', '.join(sorted(only_gen))}")
    w("")

w("### Pages with a generated list and no hand-written one")
w("")
w("Free wins — these pages currently end with no Related section at all.")
w("")
for page in sorted(RELATED):
    src = open(D(page)).read()
    if "## Related" in src:
        continue
    names = ", ".join(g["title"] for g in RELATED[page][:6])
    w(f"- `{page.replace('content/docs/free-srd/', '')}` → {names}")
w("")

path = D("_discovery/04-phase3-worksheets.md")
open(path, "w").write("\n".join(out) + "\n")
print(f"wrote {os.path.relpath(path, REPO)} ({len(out)} lines)")
print(f"  {len(tags)} tags, {len(orphans)} orphans, {len(missing)} missing summaries, "
      f"{len(IMPLICIT)} implicit edges, {len(RELATED)} pages with related data")
