#!/usr/bin/env python3
"""
worksheets.py — regenerate the Phase 3 audit worksheets from data/.

    python3 _discovery/tools/worksheets.py

Writes _discovery/04-phase3-worksheets.md: tag membership, orphaned blocks,
implicit edges, feature-prerequisite cross-checks, section-block heading
readiness, and a hand-written-vs-generated comparison of the Related sections.
Pure read + report; it never touches content. Re-run it after `builddata.py`.
"""
import json, os, re, collections

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
D = lambda *p: os.path.join(REPO, *p)

BLOCKS = json.load(open(D("data/blocks.json")))
B = {b["id"]: b for b in BLOCKS}
EDGES = json.load(open(D("data/edges.json")))
RELATED = json.load(open(D("data/related.json")))
IMPLICIT = json.load(open(D("_discovery/tools/implicit-edges.json")))

STRUCTURAL = {"equipment", "sci-fi", "core", "generic", "site-chrome", "character-creation"}
OVERVIEWISH = ("overview", "basics", "index")

out = []
w = out.append

w("# Phase 3 — audit worksheets")
w("")
w("Generated by `_discovery/tools/worksheets.py` from `data/`. Re-run it after")
w("`builddata.py` to refresh. Nothing here changes content — it is a review sheet.")
w("")
w(f"Corpus: **{len(BLOCKS)} blocks**, **{len(EDGES)} edges**, "
  f"**{sum(1 for b in BLOCKS if b.get('wip'))} wip**.")
w("")
w("---")
w("")

# ------------------------------------------------------------------ C1 tags ---
w("## C1. Tag membership")
w("")
w("Scan each list for holes — a block that belongs but is missing, or a member")
w("that does not fit. Tag names are the query surface the PDF builder will use.")
w("")
tags = collections.defaultdict(list)
for b in BLOCKS:
    for t in b.get("tags", []):
        tags[t].append(b)
for t, members in sorted(tags.items(), key=lambda kv: (-len(kv[1]), kv[0])):
    w(f"### `{t}` — {len(members)}")
    w("")
    for b in sorted(members, key=lambda b: b["id"]):
        others = [x for x in b["tags"] if x != t]
        w(f"- `{b['id']}` — {b['title']}"
          + (f"  <sub>{', '.join(others)}</sub>" if others else "  <sub>(only tag)</sub>"))
    w("")

w("### Blocks a quick-reference table would show with an empty cell")
w("")
w("`summary` is what the generated tables print. A selectable block without one")
w("renders a blank cell on every catalog and module page that lists it.")
w("")
# what a table actually lists: selectable things, plus anything a generated
# catalog points at (a rules-additions table lists rule blocks too)
catalogued = {e["target"] for e in EDGES if e.get("class") == "catalog"}
missing = [b for b in BLOCKS
           if not b.get("summary") and not b.get("excluded")
           and b.get("selectable", True)
           and (b.get("type") in ("feature", "equipment", "creature")
                or b["id"] in catalogued)]
by_type = collections.defaultdict(list)
for b in missing:
    by_type[b["type"]].append(b)
w(f"**{len(missing)} blocks**")
w("")
for t in sorted(by_type):
    w(f"*{t}*")
    w("")
    for b in sorted(by_type[t], key=lambda b: b["id"]):
        page = (b.get("source_page") or "?").replace("content/docs/free-srd/", "")
        w(f"- `{b['id']}` — {b['title']}  <sub>{page}</sub>")
    w("")

w("### Blocks with only structural tags")
w("")
w("These carry no functional tag, so a tag-as-query pull (\"give me all the")
w("grenades\") cannot reach them.")
w("")
thin = [b for b in BLOCKS
        if b.get("tags") and not (set(b["tags"]) - STRUCTURAL) and not b.get("excluded")]
if thin:
    for b in sorted(thin, key=lambda b: b["id"]):
        w(f"- `{b['id']}` — {b['title']}  <sub>{', '.join(b['tags'])}</sub>")
else:
    w("- none")
w("")
untagged = [b for b in BLOCKS if not b.get("tags")]
w(f"Blocks with no tags at all: **{len(untagged)}**"
  + ("" if not untagged else " — " + ", ".join(f"`{b['id']}`" for b in untagged)))
w("")
w("---")
w("")

# --------------------------------------------------------------- C2 orphans ---
w("## C2. Reference / edge review")
w("")
types = collections.Counter(e["type"] for e in EDGES)
w("| Edge type | Count |")
w("|---|---|")
for t, n in sorted(types.items(), key=lambda kv: -kv[1]):
    w(f"| `{t}` | {n} |")
w("")

w("### Orphans — no other block's prose points at these")
w("")
zero = [b for b in BLOCKS if b.get("in_degree", 0) == 0 and not b.get("excluded")]
listed = {e["target"] for e in EDGES if str(e["source"]).startswith("page:")}
unreachable = [b for b in zero if b["id"] not in listed]
w(f"**{len(zero)} blocks** have `in_degree: 0`, and **all but "
  f"{len(unreachable)}** of them are still reachable — they are listed in a")
w("`{{< catalog >}}` table or linked from page-frame prose. For a catalogued")
w("item (a grenade, an ability) that is the normal, expected state, so the only")
w("rows worth reviewing are the **rules and reference blocks**: a rule nothing")
w("else links to may be a missing cross-reference rather than a standalone rule.")
w("")
if unreachable:
    w("**Genuinely unreachable — not linked, not catalogued:**")
    w("")
    for b in sorted(unreachable, key=lambda b: b["id"]):
        w(f"- `{b['id']}` — {b['title']}")
    w("")
orphans = [b for b in zero
           if b.get("type") in ("rule", "reference")
           and not any(k in b["id"].split("/")[-1] for k in OVERVIEWISH)]
w(f"Rule/reference blocks with no inbound prose link: **{len(orphans)}**")
w("")
w("| Block | Type | Lives on |")
w("|---|---|---|")
for b in sorted(orphans, key=lambda b: (b.get("source_page") or "", b["id"])):
    page = (b.get("source_page") or "?").replace("content/docs/free-srd/", "")
    w(f"| `{b['id']}` — {b['title']} | {b.get('type','')} | {page} |")
w("")

w("### Implicit edges — rule couplings with no link in the prose")
w("")
w("These are invisible while reading. Decide per row: leave implicit, or write a")
w("real in-text link.")
w("")
w("| From | To | Why it is coupled |")
w("|---|---|---|")
for e in IMPLICIT:
    w(f"| `{e['source']}` | `{e['target']}` | {e.get('note','')} |")
w("")
w("---")
w("")

# ------------------------------------------------------- C4 feature prereqs ---
w("## C4. Feature prerequisites — the three places they are written")
w("")
w("A feature's prerequisites are stated in three places, each doing a different")
w("job. This section reports where they disagree, so drift surfaces instead of")
w("sitting in the data.")
w("")
w("1. **The prerequisite line** in the block's own text — what a reader sees.")
w("2. **`requires:`** in frontmatter — the mechanical rule the PDF builder obeys.")
w("   By decision it holds *features only*: attributes, levels, items and")
w("   category conditions (\"any tool kit\") stay prose.")
w("3. **The index nesting** (`- ` / `-- ` in a catalog) — where a reader meets")
w("   the entry. Recorded as `listed_under`.")
w("")
w("**2 and 3 are not the same thing and must not be merged.** They agree today,")
w("but 39 `requires` point into a different list entirely, which no index tree")
w("can show — so neither can be generated from the other.")
w("")

URL2ID = {}
for bid, b in B.items():
    if b.get("url"):
        URL2ID[b["url"]] = bid
    if b.get("anchor"):
        URL2ID.setdefault("#" + b["anchor"], bid)


def prereq_line(b):
    try:
        body = open(D(b["file"])).read().split("\n---", 1)[1]
    except (OSError, IndexError):
        return ""
    for ln in body.split("\n"):
        t = ln.strip()
        if t.startswith("*") and t.endswith("*") and not t.startswith("**") and len(t) > 4:
            return t.strip("*").strip()
    return ""


def derived_requires(b):
    """What `requires` would be if generated from the prerequisite line."""
    out = set()
    for _, url in re.findall(r"\[([^\]]+)\]\(([^)]+)\)", prereq_line(b)):
        hit = URL2ID.get(url)
        if hit and B[hit]["type"] == "feature":
            out.add(hit)
    return out


feats = [b for b in BLOCKS if b["type"] == "feature" and b["home"] == "snippet"]
drift = [(b, sorted(set(b.get("requires") or []) - derived_requires(b)),
             sorted(derived_requires(b) - set(b.get("requires") or [])))
         for b in feats]
drift = [d for d in drift if d[1] or d[2]]

w("### `requires` against the prerequisite line")
w("")
if drift:
    w(f"**{len(drift)} features disagree.** Either the line names a feature the")
    w("frontmatter does not record, or the frontmatter records one the line does")
    w("not mention.")
    w("")
    w("| Block | In `requires`, not linked in the line | Linked in the line, not in `requires` |")
    w("|---|---|---|")
    for b, missing, extra in drift:
        w(f"| `{b['id']}` | {', '.join(f'`{m}`' for m in missing) or '—'} "
          f"| {', '.join(f'`{e}`' for e in extra) or '—'} |")
else:
    w(f"**No disagreements** across {sum(1 for b in feats if b.get('requires'))} features "
      "that carry `requires`.")
    w("")
    w("Every one is exactly the set of feature links in its own prerequisite line,")
    w("which means `requires` is currently *derivable* rather than independent —")
    w("worth knowing before deciding to keep maintaining it by hand.")
w("")

w("### `requires` against the index nesting")
w("")
w("Differences here are expected — the two answer different questions. Read it")
w("as a review list, not an error list.")
w("")
nested = [b for b in BLOCKS if b.get("listed_under")]
rows = []
for b in nested:
    req = set(b.get("requires") or [])
    if b["listed_under"] in req:
        continue
    rows.append((b, req))
w(f"{len(nested)} blocks are nested in an index; **{len(rows)}** are nested under")
w("something they do not require.")
w("")
if rows:
    w("| Block | Listed under | Actually requires |")
    w("|---|---|---|")
    for b, req in rows:
        w(f"| `{b['id']}` | `{b['listed_under']}` | "
          f"{', '.join(f'`{r}`' for r in sorted(req)) or '— nothing recorded —'} |")
w("")

crossns = 0
for b in feats:
    ns = b["id"].split("/")[0]
    crossns += sum(1 for r in (b.get("requires") or []) if r.split("/")[0] != ns)
w(f"Also worth remembering: **{crossns}** `requires` point at a feature in another")
w("list (abilities depending on proficiencies or traits). No index tree can show")
w("those, which is the other reason the nesting cannot be generated from them.")
w("")
w("---")
w("")

# ---------------------------------------------------- C5 headings for print ---
w("## C5. Section-block titles — what the PDF builder will print")
w("")
w("104 blocks carry no heading of their own; the host page supplies one. Anything")
w("re-assembling them elsewhere — `{{< blockset >}}` today, the PDF builder later —")
w("prints `title` instead. For most of them that title has already been proofread,")
w("because it *is* the heading a reader sees. For a few it has never been rendered")
w("anywhere, and those are the ones that can print wrong.")
w("")
w("This is how `sci-fi/huds` was caught printing \"Huds\" instead of")
w("\"Heads Up Displays (HUDs)\".")
w("")

sec = [b for b in BLOCKS if not b["owns_heading"] and not b.get("excluded")
       and b.get("source_page")]
byhead = collections.Counter((b["source_page"], b["anchor"]) for b in sec)
shared = [b for b in sec if byhead[(b["source_page"], b["anchor"])] > 1]

w(f"### Never rendered anywhere — {len(shared)} blocks")
w("")
w("These sit under a heading they share with other blocks, so the heading names")
w("the *group*, not the block. Their own title has never appeared on the site.")
w("**Read these as headings and decide if each stands alone.**")
w("")
w("| Block | Title the builder would print | Grouped under |")
w("|---|---|---|")
for b in sorted(shared, key=lambda b: b["id"]):
    w(f"| `{b['id']}` | **{b['title']}** | `#{b['anchor']}` on "
      f"{b['source_page'].replace('content/docs/free-srd/','')} |")
w("")
w(f"The other {len(sec) - len(shared)} are the sole block under their heading, so their")
w("title is that heading and has been proofread by being read.")
w("")

w("### Heading level is the bigger print problem")
w("")
lv = collections.Counter()
for b in BLOCKS:
    if b["owns_heading"] and b["home"] == "snippet":
        try:
            body = open(D(b["file"])).read().split("\n---", 1)[1]
        except (OSError, IndexError):
            continue
        m = re.search(r"^(#{1,6})\s", body, re.M)
        if m:
            lv[len(m.group(1))] += 1
w("The blocks that *own* a heading hard-code its level in their markdown:")
w("")
for k in sorted(lv):
    w(f"- **h{k}** — {lv[k]} blocks")
w("")
w("So a GM who assembles a PDF and puts one of those at a different depth gets a")
w("heading at the wrong level, and the markdown cannot bend. The 104 blocks with")
w("*no* heading are the flexible ones — they carry a title and let whatever renders")
w("them choose the level.")
w("")
w("**The builder should print every block the same way: take `title`, choose the")
w("level from where the GM placed it, and skip the block's own leading heading")
w("when `owns_heading` is true.** That pair of fields is exactly what makes the")
w("normalisation possible — no content change needed, and the two shapes stop")
w("mattering at print time.")
w("")
w("---")
w("")

# --------------------------------------------------------------- D related ---
w("## D. Related sections — hand-written vs generated")
w("")
w("`{{< related >}}` renders the generated column. The hand-written lists carry")
w("editorial judgement the edge graph does not have (they point where a reader")
w("*should* go next, not only where the prose happens to link), so this is a")
w("per-page call, not a global swap.")
w("")
for page in sorted(RELATED):
    src = open(D(page)).read()
    hand = re.findall(r"^- \[([^\]]+)\]\(([^)]+)\)", src[src.find("## Related"):], re.M) \
        if "## Related" in src else []
    gen = RELATED[page]
    if not hand and "{{< related >}}" in src:
        continue   # already converted
    if not hand:
        continue   # no hand-written list to compare against
    w(f"### `{page.replace('content/docs/free-srd/', '')}`")
    w("")
    w("| Hand-written | Generated (in order) |")
    w("|---|---|")
    for i in range(max(len(hand), len(gen))):
        h = hand[i][0] if i < len(hand) else ""
        g = (f"{gen[i]['title']} <sub>out {gen[i]['out']} / in {gen[i]['in']}</sub>"
             if i < len(gen) else "")
        w(f"| {h} | {g} |")
    only_hand = {h[0].split(" — ")[0] for h in hand} - {g["title"] for g in gen}
    only_gen = {g["title"] for g in gen} - {h[0].split(" — ")[0] for h in hand}
    if only_hand:
        w("")
        w(f"*Generated would drop:* {', '.join(sorted(only_hand))}")
    if only_gen:
        w(f"*Generated would add:* {', '.join(sorted(only_gen))}")
    w("")

w("### Pages with a generated list and no hand-written one")
w("")
w("Free wins — these pages currently end with no Related section at all.")
w("")
for page in sorted(RELATED):
    src = open(D(page)).read()
    if "## Related" in src:
        continue
    names = ", ".join(g["title"] for g in RELATED[page][:6])
    w(f"- `{page.replace('content/docs/free-srd/', '')}` → {names}")
w("")

path = D("_discovery/04-phase3-worksheets.md")
open(path, "w").write("\n".join(out) + "\n")
print(f"wrote {os.path.relpath(path, REPO)} ({len(out)} lines)")
print(f"  {len(tags)} tags, {len(orphans)} orphans, {len(missing)} missing summaries, "
      f"{len(IMPLICIT)} implicit edges, {len(RELATED)} pages with related data")
